blockMenu.onMenuOptionSelected(function (option, index) {
    if (option == "Play") {
        color.FadeToBlack.startScreenEffect(600)
        timer.after(650, function () {
            blockMenu.setControlsEnabled(false)
            blockMenu.closeMenu()
            mySprite = sprites.create(img`
                ..................
                ..................
                ..................
                ..................
                ..................
                ..................
                ..................
                .....cccc.........
                ....cccccc........
                ....cccccc........
                ..bbcccdcd........
                .bbcaaadad........
                .bccffffff........
                .bcaaaaaaaa.......
                .bcbbbbbbbbb......
                .bcccccccccc......
                .bcccccbbbbbbbbbb.
                .ccccccbbffcbbbbb.
                ..ccfffcffffccc...
                ..ccffffcffc......
                ..cccffccccc......
                ..cccccccccc......
                ..bccccccccb......
                ...affffccc.......
                ...aaffa..........
                `, SpriteKind.Player)
            tiles.setTilemap(tilemap`level1`)
            color.startFade(color.Black, color.originalPalette)
            color.setColor(10, color.rgb(55, 43, 62))
        })
    }
})
let mySprite: Sprite = null
color.setColor(10, color.rgb(55, 43, 62))
blockMenu.showMenu(["Play"], MenuStyle.List, MenuLocation.BottomHalf)
blockMenu.setColors(10, 12)
scene.setBackgroundColor(10)
